### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by nocelab** [fustom/python-ariston-api#1]
Hi... Thank You in advance for your great library!
I'm testing it with my Genus One to understand the best configuration for the winter.
Why isn't there a Logout/Disconnect method for closing the session?

**Comment by fustom** [comment]
Hi @nocelab!
I think ariston cloud does not provide session close. At least I did not find it. Based on my experience the access token works about 30 hours after you receive it.

**Comment by nocelab** [comment]
I tried to Get `/R2/Account/Logout` and seems to correcly nullify the Access Token
