### ISSUE TITLE
Issue on use API ariston

### ISSUE THREAD

**Issue by robertomontinaro80** [fustom/python-ariston-api#137]
Hi @fustom I'm trying to use the Ariston api in order to debug my chaffoteaux thermo but with no success. I've tried to follow the example in readme but when I try to call API to get preset modes I always receive None. I can say hello and get device info with discover call. Could you explain me what is wrong with my steps? Thanks in advance.

**Comment by fustom** [comment]
First you need to get device features/data/energy data depends on what you need.
https://github.com/fustom/python-ariston-api?tab=readme-ov-file#use-your-device

**Comment by robertomontinaro80** [comment]
> First you need to get device features/data/energy data depends on what you need. https://github.com/fustom/python-ariston-api?tab=readme-ov-file#use-your-device
> 
> This method is called: "Cloud Polling" https://www.home-assistant.io/blog/2016/02/12/classifying-the-internet-of-things/#classifiers

Thanks @fustom for your answer. My objective is to retrieve the preset modes of my thermo. So I have to make those calls before to retrieve the preset modes with the call device.plant_mode_opt_texts()?

**Comment by fustom** [comment]
As may you can see [`plant_mode_opt_texts()`](https://github.com/fustom/python-ariston-api/blob/e46b0542bb026cc5b38ad3ad8da387e8e91efd58/ariston/galevo_device.py#L430) calls [`_get_item_by_id`](https://github.com/fustom/python-ariston-api/blob/e46b0542bb026cc5b38ad3ad8da387e8e91efd58/ariston/galevo_device.py#L572) who works with [`data`](https://github.com/fustom/python-ariston-api/blob/e46b0542bb026cc5b38ad3ad8da387e8e91efd58/ariston/device.py#L39). So you have to populate the data dictionary with [`update_state()`](https://github.com/fustom/python-ariston-api/blob/e46b0542bb026cc5b38ad3ad8da387e8e91efd58/ariston/galevo_device.py#L84) or [`async_update_state()`](https://github.com/fustom/python-ariston-api/blob/e46b0542bb026cc5b38ad3ad8da387e8e91efd58/ariston/galevo_device.py#L97)

**Comment by robertomontinaro80** [comment]
> As may you can see [`plant_mode_opt_texts()`](https://github.com/fustom/python-ariston-api/blob/e46b0542bb026cc5b38ad3ad8da387e8e91efd58/ariston/galevo_device.py#L430) calls [`_get_item_by_id`](https://github.com/fustom/python-ariston-api/blob/e46b0542bb026cc5b38ad3ad8da387e8e91efd58/ariston/galevo_device.py#L572) who works with [`data`](https://github.com/fustom/python-ariston-api/blob/e46b0542bb026cc5b38ad3ad8da387e8e91efd58/ariston/device.py#L39). So you have to populate the data dictionary with [`update_state()`](https://github.com/fustom/python-ariston-api/blob/e46b0542bb026cc5b38ad3ad8da387e8e91efd58/ariston/galevo_device.py#L84) or [`async_update_state()`](https://github.com/fustom/python-ariston-api/blob/e46b0542bb026cc5b38ad3ad8da387e8e91efd58/ariston/galevo_device.py#L97)

Really thank you @fustom for your kindly reply
