### ISSUE TITLE
Add get heating pump on method to galevo device

### ISSUE THREAD

**Issue by fustom** [fustom/python-ariston-api#19]
https://github.com/fustom/ariston-remotethermo-home-assistant-v3/issues/102

**Comment by samuele2723** [comment]
https://www.chaffoteaux.it/particulier/mira-advance-hybrid-link#Page1

Mira advance hybrid with external heat pump and internal boiler and it switches based on best energy saving

**Comment by fustom** [comment]
@samuele2723 
Thanks! Unfortunately I don't know anything about this device. At your home assistant what is the device type? Galevo or Velis?

**Comment by samuele2723** [comment]
Hello, the product is Chaffoteaux (ariston brand of course).

I was able to modify myself Ariston V2 integration in order to get some additonal parameter in. Any change i can support you for integration in the V3? Eventually find me on discord Steel#1232

**Comment by LarsLuttjeboer** [comment]
Item looks like this:
{
		'id': 'IsHeatingPumpOn       ',
		'zone': 0,
		'kind': 3,
		'min': 0.0,
		'max': 0.0,
		'step': 0.0,
		'value': 1.0,
		'decimals': 0,
		'options': [0, 1],
		'readOnly': True,
		'error': False,
		'   invalid': False
	}

Using ATAG Energion 15kW all-electric

**Comment by fustom** [comment]
https://github.com/fustom/python-ariston-api/pull/21
