### ISSUE TITLE
Unsupported whe type 7

### ISSUE THREAD

**Issue by DmitriyEkb196** [fustom/python-ariston-api#24]
Hi @fustom,
I have a boiler velis evo 50
Can you tell me what can be done about my mistake?

Logger: ariston
Source: /usr/local/lib/python3.10/site-packages/ariston/init.py:120
First occurred: 16:29:33 (2 occurrences)
Last logged: 16:30:17

Unsupported whe type 7
NoneType: None

**Comment by fustom** [comment]
https://github.com/fustom/ariston-remotethermo-home-assistant-v3/wiki/Unsupported-whe%7Csystem-type
