### ISSUE TITLE
Ariston Andris2 Top Wifi (Water Heater) unsupported whe type 5

### ISSUE THREAD

**Issue by Jim5975** [fustom/python-ariston-api#47]
Hi I have an Ariston Andris2 Top it used to work with chomupashchuk's integreation as a Lydos device, with the v3 it gets detected but i'm seeing an error "Unsupported whe type 5" can i make edits anywhere to get it recognized as a lydos device?

**Comment by fustom** [comment]
https://github.com/fustom/ariston-remotethermo-home-assistant-v3/wiki/Unsupported-whe%7Csystem-type
