### ISSUE TITLE
Error on Integration of Ariston Velis Lux Wi-Fi

### ISSUE THREAD

**Issue by migor7** [fustom/python-ariston-api#48]
Logger: ariston
Source: /usr/local/lib/python3.10/site-packages/ariston/__init__.py:120
First occurred: 00:53:59 (8 occurrences)
Last logged: 01:02:32

Unsupported whe type 7
NoneType: None

I am running following HA version:

Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 9.0.dev20220810
Frontend 20230503.3 - latest

**Comment by fustom** [comment]
https://github.com/fustom/ariston-remotethermo-home-assistant-v3/wiki/Unsupported-whe%7Csystem-type

**Comment by Ontry57** [comment]
Hello! My integration works bad. As I understand,  integration can’t ping my device. For example: it looks like unavailable in interface But!! After I open app - AristonNet it starts work, but short time Can u help to solve this? Best regards,  Andrei 27 авг. 2023 г., в 00:42, fustom ***@***.***> написал(а):﻿
Closed #48 as completed via #76.
